server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: never
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
logging:
  level:
    org:
      hibernate:
        sql: info